# Generated by Django 3.2.5 on 2021-08-11 08:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
