# Generated by Django 3.2.3 on 2021-07-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comments_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_on']},
        ),
    ]
